# Generated by Django 5.2.1 on 2025-06-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
    ]
