# Generated by Django 5.2.1 on 2025-07-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cart_user_alter_cart_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
